#!/usr/bin/env node

const fs = require('fs');
const babel = require('babel-core');

const res = babel.transform(fs.readFileSync(process.argv[2], 'utf-8'), {
  babelrc: false,
  presets: ['es2015', 'stage-1', 'react'],
  plugins: ['syntax-flow', require('../')],
}).code;
console.log(res);

