#!/bin/bash

fixtures="src/__test__/fixtures/"

for input_file in $fixtures/*.input.js; do
  output_file="$(echo "$input_file" | sed 's/\.input\./.output./')"
  cat "$input_file" | ./node_modules/.bin/babel --plugins syntax-flow,./lib/index.js --presets es2015 > "$output_file"
done

