#!/bin/bash

fixtures="src/__test__/fixtures"

for input_file in $fixtures/*.input.js; do
  output_file="$(echo "$input_file" | sed 's/\.input\./.output./')"
  printf '%sProp types for '%s':%s\n' "$(tput setaf 3)" "$output_file" "$(tput sgr0)"
  cat "$input_file" | ./node_modules/.bin/babel --plugins syntax-flow,./lib/index.js --presets es2015,react,stage-1 > "$output_file"

  sed -n '/\.propTypes =/,/^};/p' $output_file
  echo
done

